#!/bin/bash
echo "Please verify your Supabase credentials:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/xswknojsvovbzhcpgizw/settings/database"
echo ""
echo "2. Check:"
echo "   - Is your database password: 'juzDac-2biqqo-pyphaz'?"
echo "   - Or did you recently reset it?"
echo ""
echo "3. Look for the 'Connection string' section and find:"
echo "   - Transaction Pooler (recommended)"
echo "   - Copy the exact connection string"
echo ""
echo "4. We're currently trying to connect with:"
echo "   - Pooler: postgresql://postgres.xswknojsvovbzhcpgizw:[PASSWORD]@aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres"
echo ""
echo "Please check if the password is correct or if there's a different connection string."
