services:
  app:
    build: .
    restart: always
    ports:
      - "8501:8501"  # Streamlit port
      - "5001:5001"  # Webhook server port
    environment:
      # This URL allows the app to connect to the 'db' service.
      - DATABASE_URL=postgresql://user:password@db:5432/meiyumedb
    depends_on:
      - db
    volumes:
      # This mounts your local code into the container, so changes are reflected instantly.
      - .:/app

  db:
    image: postgres:13
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: meiyumedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      # This ensures your database data is persistent across restarts.
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
