# Generated by Django 4.2.7 on 2025-06-23 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CADUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='cad_files/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(help_text='SHA256 hash of the file', max_length=64)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('drawing_number', models.CharField(blank=True, max_length=100, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('n8n_execution_id', models.CharField(blank=True, max_length=100, null=True)),
                ('webhook_response', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cad_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_extract_dimensions', models.BooleanField(default=True)),
                ('default_extract_tolerances', models.BooleanField(default=True)),
                ('default_analyze_relationships', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('processing_complete_notifications', models.BooleanField(default=True)),
                ('azure_ad_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cad_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('dimensions', 'Dimensions'), ('tolerances', 'Tolerances'), ('relationships', 'Part Relationships'), ('materials', 'Materials'), ('assembly', 'Assembly Components')], max_length=20)),
                ('raw_data', models.JSONField(help_text='Raw JSON data from AI analysis')),
                ('processed_data', models.JSONField(blank=True, help_text='Processed/cleaned data', null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('extraction_method', models.CharField(default='gemini-ai', max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('csv_file_path', models.FileField(blank=True, null=True, upload_to='results/csv/%Y/%m/%d/')),
                ('report_file_path', models.FileField(blank=True, null=True, upload_to='results/reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='cad_core.cadupload')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract_dimensions', models.BooleanField(default=True)),
                ('extract_tolerances', models.BooleanField(default=True)),
                ('analyze_part_relationships', models.BooleanField(default=True)),
                ('extract_material_specifications', models.BooleanField(default=False)),
                ('detect_assembly_components', models.BooleanField(default=False)),
                ('ai_model_version', models.CharField(default='gemini-pro', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.8)),
                ('max_analysis_time', models.PositiveIntegerField(default=300)),
                ('custom_prompt_additions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_options', to='cad_core.cadupload')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('debug', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('step', models.CharField(help_text="Processing step (e.g., 'file_upload', 'ai_analysis', 'result_generation')", max_length=100)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='cad_core.cadupload')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['upload', 'level'], name='cad_core_pr_upload__dc7d28_idx'), models.Index(fields=['created_at'], name='cad_core_pr_created_74dbe7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cadupload',
            index=models.Index(fields=['user', 'status'], name='cad_core_ca_user_id_621307_idx'),
        ),
        migrations.AddIndex(
            model_name='cadupload',
            index=models.Index(fields=['created_at'], name='cad_core_ca_created_2d45bc_idx'),
        ),
        migrations.AddIndex(
            model_name='cadupload',
            index=models.Index(fields=['file_hash'], name='cad_core_ca_file_ha_87dece_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['upload', 'result_type'], name='cad_core_an_upload__87aa4b_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['created_at'], name='cad_core_an_created_5a3f92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='analysisresult',
            unique_together={('upload', 'result_type')},
        ),
    ]
