# Generated by Django 4.2.7 on 2025-06-30 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cad_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processinglog',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='cad_core.cadupload'),
        ),
    ]
