# Generated by Django 4.2.7 on 2025-07-02 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CADUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash of the file", max_length=64
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                (
                    "n8n_execution_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("webhook_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drawing_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("revision", models.CharField(blank=True, max_length=50, null=True)),
                ("file_path", models.FileField(upload_to="cad_files/%Y/%m/%d/")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CAD Upload",
                "verbose_name_plural": "CAD Uploads",
            },
        ),
        migrations.CreateModel(
            name="CADAnalysisOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_model_version",
                    models.CharField(default="gemini-pro", max_length=50),
                ),
                ("confidence_threshold", models.FloatField(default=0.8)),
                ("max_analysis_time", models.PositiveIntegerField(default=300)),
                ("custom_prompt_additions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("extract_dimensions", models.BooleanField(default=True)),
                ("extract_tolerances", models.BooleanField(default=True)),
                ("analyze_part_relationships", models.BooleanField(default=True)),
                ("extract_material_specifications", models.BooleanField(default=False)),
                ("detect_assembly_components", models.BooleanField(default=False)),
                (
                    "upload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_options",
                        to="cad.cadupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAD Analysis Options",
                "verbose_name_plural": "CAD Analysis Options",
            },
        ),
        migrations.CreateModel(
            name="CADAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(help_text="Raw JSON data from AI analysis"),
                ),
                (
                    "processed_data",
                    models.JSONField(
                        blank=True, help_text="Processed/cleaned data", null=True
                    ),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                (
                    "extraction_method",
                    models.CharField(default="gemini-ai", max_length=50),
                ),
                ("processing_time_seconds", models.FloatField(blank=True, null=True)),
                (
                    "csv_file_path",
                    models.FileField(
                        blank=True, null=True, upload_to="results/csv/%Y/%m/%d/"
                    ),
                ),
                (
                    "report_file_path",
                    models.FileField(
                        blank=True, null=True, upload_to="results/reports/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result_type",
                    models.CharField(
                        choices=[
                            ("dimensions", "Dimensions"),
                            ("tolerances", "Tolerances"),
                            ("relationships", "Part Relationships"),
                            ("materials", "Materials"),
                            ("assembly", "Assembly Components"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="cad.cadupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAD Analysis Result",
                "verbose_name_plural": "CAD Analysis Results",
                "unique_together": {("upload", "result_type")},
            },
        ),
    ]
