# Generated by Django 4.2.7 on 2025-08-04 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated from first message",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "session_config",
                    models.JSONField(
                        default=dict, help_text="Chat configuration and preferences"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quality Chat Session",
                "verbose_name_plural": "Quality Chat Sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="QualityMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("document", "Document Upload"),
                            ("image", "Image"),
                            ("error", "Error Message"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "rag_context",
                    models.JSONField(
                        blank=True,
                        help_text="Retrieved documents and context used",
                        null=True,
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                (
                    "n8n_execution_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("n8n_response", models.JSONField(blank=True, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional message metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="quality.qualitychat",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Message",
                "verbose_name_plural": "Quality Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityKnowledgeBase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("procedure", "Procedure"),
                            ("guideline", "Guideline"),
                            ("template", "Template"),
                            ("policy", "Policy"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "tags",
                    models.JSONField(default=list, help_text="Tags for categorization"),
                ),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether entry is available for RAG"
                    ),
                ),
                (
                    "vector_embedding",
                    models.JSONField(
                        blank=True,
                        help_text="Vector embedding for similarity search",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_kb_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Knowledge Base Entry",
                "verbose_name_plural": "Quality Knowledge Base Entries",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="QualityDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash of the file", max_length=64
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processing_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "processing_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                (
                    "n8n_execution_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("webhook_response", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("sop", "Standard Operating Procedure"),
                            ("manual", "Quality Manual"),
                            ("specification", "Product Specification"),
                            ("report", "Quality Report"),
                            ("checklist", "Quality Checklist"),
                            ("other", "Other Document"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "file_path",
                    models.FileField(upload_to="quality_documents/%Y/%m/%d/"),
                ),
                (
                    "is_indexed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether document is indexed in vector database",
                    ),
                ),
                (
                    "vector_store_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in vector store",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Document",
                "verbose_name_plural": "Quality Documents",
            },
        ),
        migrations.AddField(
            model_name="qualitychat",
            name="context_documents",
            field=models.ManyToManyField(
                blank=True,
                help_text="Documents available for RAG context",
                to="quality.qualitydocument",
            ),
        ),
        migrations.AddField(
            model_name="qualitychat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_chats",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
