# Generated by Django 4.2.7 on 2025-08-06 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityChatAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("user_messages", models.IntegerField(default=0)),
                ("assistant_messages", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("average_response_time", models.FloatField(blank=True, null=True)),
                ("topics_discussed", models.JSONField(blank=True, default=list)),
                ("session_duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quality_chat_analytics",
            },
        ),
        migrations.CreateModel(
            name="QualityChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("assistant", "Assistant Response"),
                            ("system", "System Message"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("response_time", models.FloatField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(blank=True, null=True)),
                ("model_used", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "quality_chat_messages",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="QualityChatResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("partial", "Partial Success"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("n8n_webhook_url", models.URLField()),
                ("n8n_response", models.JSONField(blank=True, default=dict)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_details",
                        to="quality.qualitychatmessage",
                    ),
                ),
            ],
            options={
                "db_table": "quality_chat_responses",
            },
        ),
        migrations.CreateModel(
            name="QualityChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quality_chat_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RemoveField(
            model_name="qualitydocument",
            name="user",
        ),
        migrations.RemoveField(
            model_name="qualitymessage",
            name="chat",
        ),
        migrations.AlterModelOptions(
            name="qualityknowledgebase",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="qualityknowledgebase",
            name="category",
        ),
        migrations.RemoveField(
            model_name="qualityknowledgebase",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="qualityknowledgebase",
            name="vector_embedding",
        ),
        migrations.AddField(
            model_name="qualityknowledgebase",
            name="source",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="qualityknowledgebase",
            name="version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="qualityknowledgebase",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("standard", "Quality Standard"),
                    ("procedure", "Testing Procedure"),
                    ("guideline", "Best Practice Guideline"),
                    ("regulation", "Regulation/Compliance"),
                    ("faq", "Frequently Asked Question"),
                ],
                default="guideline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="qualityknowledgebase",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="qualityknowledgebase",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="qualityknowledgebase",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterModelTable(
            name="qualityknowledgebase",
            table="quality_knowledge_base",
        ),
        migrations.DeleteModel(
            name="QualityChat",
        ),
        migrations.DeleteModel(
            name="QualityDocument",
        ),
        migrations.DeleteModel(
            name="QualityMessage",
        ),
        migrations.AddField(
            model_name="qualitychatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="quality.qualitychatsession",
            ),
        ),
        migrations.AddField(
            model_name="qualitychatanalytics",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to="quality.qualitychatsession",
            ),
        ),
    ]
